/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbiblioteca.vistas;

import appbiblioteca.negocio.EventosDlgAltaLibros;
import appbiblioteca.persistencia.ManejaTablaH;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Jorge
 */
public class DlgAltaLibros extends javax.swing.JDialog {

    
    private final Font fuenteL= new Font("Helvetica",Font.PLAIN,12);
    private final Font fuenteT= new Font("Helvetica",Font.BOLD,20);
    private final Font fuenteB= new Font("Helvetica",Font.BOLD,13);
    private final Color COLOR_MEDIO = new Color(0, 176, 255);
    private final Color COLOR_LIGHT = new Color(105, 226, 255);
    private final Color COLOR_DARK = new Color(0, 129, 203);
    
    EventosDlgAltaLibros controladoraLibros;
    
    /**
     * Creates new form DlgAltaLibros
     */
    public DlgAltaLibros(java.awt.Frame frame,String title, boolean modal, ManejaTablaH tablaH) {
        super(frame,title, modal);
        initComponents();
        creaAcciones(tablaH);
    }
    
    private void creaAcciones(ManejaTablaH tablaH){
        controladoraLibros = new EventosDlgAltaLibros(this, tablaH);
        
        this.btnAltaLibAgregar.addActionListener(controladoraLibros);
        this.btnAltaLibSalir.addActionListener(controladoraLibros);        
    }
    
    public String getNombre(){
        return this.txtAltaLibNombre.getText();
    }
    public String getDescripcion(){
        return this.txtAltaLibDescripcion.getText();
    }
    public String getAutor(){
        return this.txtAltaLibAutor.getText();
    }
    public String getEditorial(){
        return this.txtAltaLibEditorial.getText();
    }
    
    public void limpiarTxt(){
        this.txtAltaLibAutor.setText("");
        this.txtAltaLibClave.setText("");
        this.txtAltaLibDescripcion.setText("");
        this.txtAltaLibEditorial.setText("");
        this.spnAltaLibrosExistencia.setValue(0);
        this.txtAltaLibNombre.setText("");
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtAltaLibClave = new javax.swing.JTextField();
        txtAltaLibNombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAltaLibDescripcion = new javax.swing.JTextArea();
        txtAltaLibAutor = new javax.swing.JTextField();
        txtAltaLibEditorial = new javax.swing.JTextField();
        btnAltaLibAgregar = new javax.swing.JButton();
        btnAltaLibSalir = new javax.swing.JButton();
        spnAltaLibrosExistencia = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Libros");
        setLocationByPlatform(true);
        setModal(true);
        setName("Altas Libros"); // NOI18N
        setResizable(false);

        jLabel1.setFont(fuenteL);
        jLabel1.setText("Clave");

        jLabel2.setFont(fuenteL);
        jLabel2.setText("Nombre");

        jLabel3.setFont(fuenteT);
        jLabel3.setText("Alta de Libros");

        jLabel4.setFont(fuenteL);
        jLabel4.setText("Descripcion");

        jLabel5.setFont(fuenteL);
        jLabel5.setText("Autor");

        jLabel6.setFont(fuenteL);
        jLabel6.setText("Existencia");

        jLabel7.setFont(fuenteL);
        jLabel7.setText("Editorial");

        txtAltaLibClave.setBorder(null);
        txtAltaLibClave.setPreferredSize(new java.awt.Dimension(50, 25));

        txtAltaLibNombre.setBorder(null);
        txtAltaLibNombre.setPreferredSize(new java.awt.Dimension(50, 25));

        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        txtAltaLibDescripcion.setColumns(4);
        txtAltaLibDescripcion.setRows(4);
        txtAltaLibDescripcion.setBorder(null);
        jScrollPane1.setViewportView(txtAltaLibDescripcion);

        txtAltaLibAutor.setBorder(null);
        txtAltaLibAutor.setPreferredSize(new java.awt.Dimension(50, 25));

        txtAltaLibEditorial.setBorder(null);
        txtAltaLibEditorial.setPreferredSize(new java.awt.Dimension(50, 25));

        btnAltaLibAgregar.setBackground(COLOR_MEDIO);
        btnAltaLibAgregar.setFont(fuenteB);
        btnAltaLibAgregar.setText("Agregar");
        btnAltaLibAgregar.setBorder(null);
        btnAltaLibAgregar.setPreferredSize(new java.awt.Dimension(100, 30));

        btnAltaLibSalir.setBackground(COLOR_MEDIO);
        btnAltaLibSalir.setFont(fuenteB);
        btnAltaLibSalir.setText("Salir");
        btnAltaLibSalir.setBorder(null);
        btnAltaLibSalir.setPreferredSize(new java.awt.Dimension(100, 30));

        spnAltaLibrosExistencia.setFont(fuenteL);
        spnAltaLibrosExistencia.setBorder(null);
        spnAltaLibrosExistencia.setPreferredSize(new java.awt.Dimension(29, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtAltaLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtAltaLibEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(spnAltaLibrosExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAltaLibClave, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtAltaLibNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(503, 503, 503)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAltaLibAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAltaLibSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltaLibClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltaLibNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltaLibEditorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAltaLibAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAltaLibrosExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAltaLibSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAltaLibAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaLibAgregar;
    private javax.swing.JButton btnAltaLibSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnAltaLibrosExistencia;
    private javax.swing.JTextField txtAltaLibAutor;
    private javax.swing.JTextField txtAltaLibClave;
    private javax.swing.JTextArea txtAltaLibDescripcion;
    private javax.swing.JTextField txtAltaLibEditorial;
    private javax.swing.JTextField txtAltaLibNombre;
    // End of variables declaration//GEN-END:variables
}
