package appbiblioteca.vistas;

import recursos.MaterialBtn;
import recursos.MaterialTxtField;
import appbiblioteca.negocio.EventosDlgAltaUsuarios;
import appbiblioteca.persistencia.ManejaTablaH;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Jorge
 */
public class DlgAltaUsuarios extends javax.swing.JDialog {

    private final Font fuenteH= new Font("Helvetica",Font.BOLD,20);
    private final Font fuenteT= new Font("Helvetica",Font.PLAIN,14);
    private final Font fuenteB= new Font("Helvetica",Font.BOLD,13);
    private final Color COLOR_MEDIO = new Color(0, 176, 255);
    private final Color COLOR_LIGHT = new Color(105, 226, 255);
    private final Color COLOR_DARK = new Color(0, 129, 203);
    
    EventosDlgAltaUsuarios controladoraUsuarios;
    
    
    public DlgAltaUsuarios(java.awt.Frame frame, String title ,boolean modal, ManejaTablaH tablaH) {
        super(frame,title, modal);
        initComponents();
        creaAcciones(tablaH);
    }
    
    private void creaAcciones(ManejaTablaH tablaH){
        controladoraUsuarios = new EventosDlgAltaUsuarios(this, tablaH);
        
        btnAltaUsuarioAgregar.addActionListener(controladoraUsuarios);
        btnAltaUsuarioSalir.addActionListener(controladoraUsuarios);        
    }
    
    public void limpiarTxt(){
        txtAltaUsuarioNombre.setText("");
        txtAltaUsuarioApeMat.setText("");
        txtAltaUsuarioApePat.setText("");
        txtAltaUsuarioCiudad.setText("");
        txtAltaUsuarioDomicilio.setText("");
        cmbTipo.setSelectedIndex(0);
    }
    
    
    public String getUsuarioNombre(){
        return txtAltaUsuarioNombre.getText();
    }
    public String getUsuarioApeMat(){
        return txtAltaUsuarioApeMat.getText();
    }
    public String getUsuarioApePat(){
        return txtAltaUsuarioApePat.getText();
    }
    public String getUsuarioCiudad(){
        return txtAltaUsuarioCiudad.getText();
    }
    public String getUsuarioDomicilio(){
        return txtAltaUsuarioDomicilio.getText();
    }
    public char getUsuarioTipo(){
        return cmbTipo.getSelectedItem().toString().charAt(0);
    }   
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        txtAltaUsuarioApeMat = new MaterialTxtField("Apellido Materno");
        cmbTipo = new javax.swing.JComboBox<>();
        txtAltaUsuarioCiudad = new MaterialTxtField("Ciudad de Residencia");
        btnAltaUsuarioAgregar = new MaterialBtn("Agregar");
        btnAltaUsuarioSalir = new MaterialBtn("Salir");
        txtAltaUsuarioApePat = new MaterialTxtField("Apellido Paterno");
        txtAltaUsuarioNombre = new MaterialTxtField("Nombre");
        jLabel8 = new javax.swing.JLabel();
        txtAltaUsuarioDomicilio = new MaterialTxtField("Descripcion");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta de Usuarios");
        setBackground(new java.awt.Color(255, 255, 255));
        setModal(true);
        setResizable(false);

        txtAltaUsuarioApeMat.setFont(fuenteT);
        txtAltaUsuarioApeMat.setBorder(null);
        txtAltaUsuarioApeMat.setMinimumSize(new java.awt.Dimension(0, 20));
        txtAltaUsuarioApeMat.setPreferredSize(new java.awt.Dimension(100, 40));

        cmbTipo.setBackground(Color.WHITE);
        cmbTipo.setFont(fuenteT);
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Alumno", "Maestro", "Externo" }));
        cmbTipo.setBorder(null);
        cmbTipo.setPreferredSize(new java.awt.Dimension(0, 25));
        cmbTipo.getComponent(0).setBackground(new Color(224, 224, 224, 255));

        txtAltaUsuarioCiudad.setFont(fuenteT);
        txtAltaUsuarioCiudad.setBorder(null);
        txtAltaUsuarioCiudad.setPreferredSize(new java.awt.Dimension(100, 40));

        btnAltaUsuarioAgregar.setBackground(COLOR_MEDIO);
        btnAltaUsuarioAgregar.setFont(fuenteB);
        btnAltaUsuarioAgregar.setForeground(Color.BLACK);
        btnAltaUsuarioAgregar.setText("Agregar");
        btnAltaUsuarioAgregar.setBorder(null);
        btnAltaUsuarioAgregar.setFocusPainted(false);
        btnAltaUsuarioAgregar.setPreferredSize(new java.awt.Dimension(100, 30));

        btnAltaUsuarioSalir.setBackground(COLOR_MEDIO);
        btnAltaUsuarioSalir.setFont(fuenteB);
        btnAltaUsuarioSalir.setForeground(Color.BLACK);
        btnAltaUsuarioSalir.setText("Salir");
        btnAltaUsuarioSalir.setBorder(null);
        btnAltaUsuarioSalir.setFocusPainted(false);
        btnAltaUsuarioSalir.setPreferredSize(new java.awt.Dimension(100, 30));

        txtAltaUsuarioApePat.setFont(fuenteT);
        txtAltaUsuarioApePat.setBorder(null);
        txtAltaUsuarioApePat.setMinimumSize(new java.awt.Dimension(0, 20));
        txtAltaUsuarioApePat.setPreferredSize(new java.awt.Dimension(100, 40));

        txtAltaUsuarioNombre.setFont(fuenteT);
        txtAltaUsuarioNombre.setBorder(null);
        txtAltaUsuarioNombre.setMinimumSize(new java.awt.Dimension(0, 20));
        txtAltaUsuarioNombre.setPreferredSize(new java.awt.Dimension(100, 40));

        jLabel8.setFont(fuenteH);
        jLabel8.setText("Alta de Usuarios");

        txtAltaUsuarioDomicilio.setFont(new Font("Helvetica", Font.PLAIN,13));
        txtAltaUsuarioDomicilio.setBorder(null);
        txtAltaUsuarioDomicilio.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAltaUsuarioDomicilio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAltaUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAltaUsuarioApePat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAltaUsuarioApeMat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAltaUsuarioCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAltaUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAltaUsuarioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAltaUsuarioNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltaUsuarioApePat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAltaUsuarioApeMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtAltaUsuarioDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAltaUsuarioCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmbTipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAltaUsuarioSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAltaUsuarioAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltaUsuarioAgregar;
    private javax.swing.JButton btnAltaUsuarioSalir;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAltaUsuarioApeMat;
    private javax.swing.JTextField txtAltaUsuarioApePat;
    private javax.swing.JTextField txtAltaUsuarioCiudad;
    private javax.swing.JTextField txtAltaUsuarioDomicilio;
    private javax.swing.JTextField txtAltaUsuarioNombre;
    // End of variables declaration//GEN-END:variables
}
