/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbiblioteca.vistas;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Jorge
 */
public class DlgPrestamos extends javax.swing.JDialog {
    
        
    private final Font fuenteH= new Font("Helvetica",Font.PLAIN,12);
    private final Font fuenteT= new Font("Helvetica",Font.BOLD,20);
    private final Font fuenteB= new Font("Helvetica",Font.BOLD,13);
    private final Color COLOR_MEDIO = new Color(0, 176, 255);
    private final Color COLOR_LIGHT = new Color(105, 226, 255);
    private final Color COLOR_DARK = new Color(0, 129, 203);

    /**
     * Creates new form DlgPrestamos
     */
    public DlgPrestamos(java.awt.Frame parent,String title, boolean modal) {
        super(parent,title, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPresLibClave = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnPresLibBuscar = new javax.swing.JButton();
        txtPresLibNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPresLibExistencia = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPresLibMorosidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnPresLibPrestar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtPresLibUsuario = new javax.swing.JTextField();
        btnPresLibBuscarUs = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Prestamo de Libros");
        setLocationByPlatform(true);
        setModal(true);
        setResizable(false);

        jLabel1.setFont(fuenteT);
        jLabel1.setText("Prestamo de Libros");

        txtPresLibClave.setFont(fuenteH);
        txtPresLibClave.setBorder(null);

        jLabel2.setFont(fuenteH);
        jLabel2.setText("Clave");

        btnPresLibBuscar.setBackground(COLOR_LIGHT);
        btnPresLibBuscar.setFont(fuenteB);
        btnPresLibBuscar.setText("Buscar");
        btnPresLibBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.DARK_GRAY));
        btnPresLibBuscar.setFocusPainted(false);
        btnPresLibBuscar.setOpaque(false);
        btnPresLibBuscar.setPreferredSize(new java.awt.Dimension(34, 30));

        txtPresLibNombre.setEditable(false);
        txtPresLibNombre.setFont(fuenteB);
        txtPresLibNombre.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.lightGray));

        jLabel3.setFont(fuenteH);
        jLabel3.setText("Nombre Libro");

        txtPresLibExistencia.setEditable(false);
        txtPresLibExistencia.setFont(fuenteB);
        txtPresLibExistencia.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.lightGray));

        jLabel4.setFont(fuenteH);
        jLabel4.setText("Existencia");

        txtPresLibMorosidad.setEditable(false);
        txtPresLibMorosidad.setFont(fuenteH);
        txtPresLibMorosidad.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.lightGray));

        jLabel5.setFont(fuenteH);
        jLabel5.setText("Morosidad");

        btnPresLibPrestar.setBackground(COLOR_MEDIO);
        btnPresLibPrestar.setFont(fuenteB);
        btnPresLibPrestar.setText("Prestar");
        btnPresLibPrestar.setBorderPainted(false);
        btnPresLibPrestar.setFocusPainted(false);
        btnPresLibPrestar.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel6.setFont(fuenteH);
        jLabel6.setText("Usuario");

        txtPresLibUsuario.setFont(fuenteH);
        txtPresLibUsuario.setBorder(null);
        txtPresLibUsuario.setPreferredSize(new java.awt.Dimension(6, 30));

        btnPresLibBuscarUs.setBackground(new Color(240,240,240));
        btnPresLibBuscarUs.setFont(fuenteB);
        btnPresLibBuscarUs.setText("Buscar");
        btnPresLibBuscarUs.setActionCommand("btnDevLibBuscarUs");
        btnPresLibBuscarUs.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.DARK_GRAY));
        btnPresLibBuscarUs.setFocusPainted(false);
        btnPresLibBuscarUs.setOpaque(false);
        btnPresLibBuscarUs.setPreferredSize(new java.awt.Dimension(34, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPresLibPrestar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPresLibNombre)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtPresLibMorosidad, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(txtPresLibExistencia))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91)
                                .addComponent(jLabel4))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtPresLibUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtPresLibClave, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnPresLibBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(btnPresLibBuscarUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPresLibClave, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPresLibBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPresLibUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPresLibBuscarUs, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPresLibNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPresLibMorosidad, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPresLibExistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnPresLibPrestar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPresLibBuscar;
    private javax.swing.JButton btnPresLibBuscarUs;
    private javax.swing.JButton btnPresLibPrestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField txtPresLibClave;
    private javax.swing.JTextField txtPresLibExistencia;
    private javax.swing.JTextField txtPresLibMorosidad;
    private javax.swing.JTextField txtPresLibNombre;
    private javax.swing.JTextField txtPresLibUsuario;
    // End of variables declaration//GEN-END:variables
}
