/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbiblioteca.vistas;

import appbiblioteca.modelo.Prestamo;
import appbiblioteca.persistencia.ManejaTablaH;
import java.awt.Frame;
import java.util.List;
import java.util.Objects;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge
 */
public class DlgReportePrestados extends javax.swing.JDialog {
private ManejaTablaH tablaH;

    /**
     * Creates new form DlgReportePrestados
     */
    public DlgReportePrestados(Frame frame, String title, boolean modal, ManejaTablaH mt) {
        super(frame,title,modal);
        tablaH=mt;
        initComponents();
        llenarTabla();
    }

    public JTable getTblReportePrestados() {
        return tblReportePrestados;
    }
    
    public void llenarTabla(){
        
        
        DefaultTableModel modelo =
                        (DefaultTableModel) getTblReportePrestados().getModel();
                          
                List<Prestamo[]> lista= tablaH.getTablaPrestamos().getAllPrestamos();
               
                modelo.setRowCount(0);

                Object matrix[] = new Object[5];
                 System.out.println(lista.size());   
                for (int i = 0; i < lista.size(); i++) {
                    Prestamo[] prestam =lista.get(i);
                    for (int j = 0; j <prestam.length ; j++) {
                    if(!Objects.isNull(prestam[j])){    
                    matrix[0] = prestam[j].getNombreUsuario();
                    matrix[1] = prestam[j].getLibroPrestado();
                    matrix[2] = prestam[j].getDiaPrestamo();
                     modelo.addRow(matrix);
                    }    
                    
                   
                    }
             

                }

               getTblReportePrestados().setModel(modelo);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblReportePrestados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblReportePrestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre de Usuario", "Libro Prestado", "Fecha Prestamo"
            }
        ));
        tblReportePrestados.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(tblReportePrestados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReportePrestados;
    // End of variables declaration//GEN-END:variables
}
