/*                    
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbiblioteca.vistas;


import appbiblioteca.negocio.ManejaEventos;
import appbiblioteca.modelo.Libro;
import appbiblioteca.persistencia.ManejaLista;
import appbiblioteca.persistencia.ManejaTablaH;
import appbiblioteca.modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.Box;

/**
 *
 * @author Jorge
 */
public class VistaBiblioteca extends javax.swing.JFrame {
    
    private final Font fuenteH= new Font("Helvetica",Font.PLAIN,13);
    private final Font fuenteT= new Font("Helvetica",Font.PLAIN,15);
    private final Color COLOR_MEDIO = new Color(0, 176, 255);
    private final Color COLOR_LIGHT = new Color(105, 226, 255);
    private final Color COLOR_DARK = new Color(0, 129, 203);
    
    private ManejaTablaH tablaH;
    private ManejaLista lista;

    public VistaBiblioteca() {
        
        tablaH = new ManejaTablaH();
        lista = new ManejaLista(tablaH);
        initComponents();
        creaAcciones();
        
        // Usuarios Agregados Inicialmente Para hacer Pruebas
        Usuario pedro = new Usuario("PEDRO", "PEREZ", "LOPEZ", "LAS QUINTAS", "CULIACAN", 'A');
        Usuario hernan = new Usuario("HERNAN", "ROSALES", "CORVERA", "POR AHI", "CULIACAN", 'M');
        Usuario armando = new Usuario("ARMANDO", "BELTRAN", "MEDINA", "DOMICILIO CONOCIDO", "CULIACAN", 'E');

        tablaH.AgregaUsuario(pedro);
        tablaH.AgregaUsuario(hernan);
        tablaH.AgregaUsuario(armando);
        
        // Libros Agregados Inicialmente Para Hacer Pruebas
        Libro libro1 = new Libro("GAME OF THRONES", "GEORGE R.R MARTIN",
                "LIBRO DE FANTASIA MEDIEVAL", "NO SE", 5);
        Libro libro2 = new Libro("HARRY POTTER Y LA PIEDRA FILOSOFAL", "J.K ROWLINS", "LIBRO DE FANTASIA MAGICA Y HECHICERIA", "BLOOMSBURY PUBLISHING", 6);
        
        tablaH.AgregaLibro(libro1);
        tablaH.AgregaLibro(libro2);
                
        pedro.setMoroso(true);
        
    }
    
    private void creaAcciones(){
        
        ManejaEventos controladora = new ManejaEventos(this,tablaH, lista);
        menuItmSalir.addActionListener(controladora);
        mnItmAltasUsuario.addActionListener(controladora);
        mnItmAltaLibros.addActionListener(controladora);
        mnItmExistencia.addActionListener(controladora);
        mnItmPrestamoLibros.addActionListener(controladora);
        mnItmDevolucionLibros.addActionListener(controladora);
        mnItmBusqueda.addActionListener(controladora);
        mnItmReporteUsuarios.addActionListener(controladora);
        mnItmAcerca.addActionListener(controladora);
        mnItmInventario.addActionListener(controladora);
        mnItmMorosos.addActionListener(controladora);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mbBarraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItmSalir = new javax.swing.JMenuItem();
        menuGestion = new javax.swing.JMenu();
        mnItmAltasUsuario = new javax.swing.JMenuItem();
        mnItmAltaLibros = new javax.swing.JMenuItem();
        mnItmExistencia = new javax.swing.JMenuItem();
        mnItmMorosos = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        mnItmBusqueda = new javax.swing.JMenuItem();
        mnItmReporteUsuarios = new javax.swing.JMenuItem();
        mnItmInventario = new javax.swing.JMenuItem();
        menuLibros = new javax.swing.JMenu();
        mnItmPrestamoLibros = new javax.swing.JMenuItem();
        mnItmDevolucionLibros = new javax.swing.JMenuItem();
        menuAcerca = new javax.swing.JMenu();
        mnItmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setBackground(Color.WHITE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/2x/book-2-24.png")));
        setLocationByPlatform(true);
        setName("VistaBiblioteca"); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, Color.lightGray));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 778, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 534, Short.MAX_VALUE)
        );

        mbBarraMenu.setBackground(COLOR_MEDIO);
        mbBarraMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, COLOR_LIGHT, COLOR_MEDIO, COLOR_DARK, COLOR_MEDIO));

        menuArchivo.setForeground(Color.BLACK);
        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_menuG.png"))); // NOI18N
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(fuenteT);
        menuArchivo.setIconTextGap(10);

        menuItmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        menuItmSalir.setFont(fuenteH);
        menuItmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_close_black_18dp.png"))); // NOI18N
        menuItmSalir.setText("Salir");
        menuArchivo.add(menuItmSalir);

        mbBarraMenu.add(menuArchivo);

        menuGestion.setForeground(Color.BLACK);
        menuGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_addG.png"))); // NOI18N
        menuGestion.setText("Gestion");
        menuGestion.setFont(fuenteT);
        menuGestion.setIconTextGap(10);

        mnItmAltasUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmAltasUsuario.setFont(fuenteH);
        mnItmAltasUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_person_add_black_18dp.png"))); // NOI18N
        mnItmAltasUsuario.setText("Altas Usuario");
        menuGestion.add(mnItmAltasUsuario);

        mnItmAltaLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmAltaLibros.setFont(fuenteH);
        mnItmAltaLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_library_add_black_18dp.png"))); // NOI18N
        mnItmAltaLibros.setText("Alta Libros");
        menuGestion.add(mnItmAltaLibros);

        mnItmExistencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmExistencia.setFont(fuenteH);
        mnItmExistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_addchart_black_18dp.png"))); // NOI18N
        mnItmExistencia.setText("Aumentar Existencia");
        menuGestion.add(mnItmExistencia);

        mnItmMorosos.setFont(fuenteH);
        mnItmMorosos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_add_black_18dp.png"))); // NOI18N
        mnItmMorosos.setText("Morosos");
        menuGestion.add(mnItmMorosos);

        mbBarraMenu.add(menuGestion);

        menuConsultas.setForeground(Color.BLACK);
        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_search_black_18dp.png"))); // NOI18N
        menuConsultas.setText("Consultas");
        menuConsultas.setFont(fuenteT);
        menuConsultas.setIconTextGap(10);

        mnItmBusqueda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmBusqueda.setFont(fuenteH);
        mnItmBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_search_black_18dp.png"))); // NOI18N
        mnItmBusqueda.setText("Busqueda");
        menuConsultas.add(mnItmBusqueda);

        mnItmReporteUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmReporteUsuarios.setFont(fuenteH);
        mnItmReporteUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_search_black_18dp.png"))); // NOI18N
        mnItmReporteUsuarios.setText("Reporte Usuarios");
        menuConsultas.add(mnItmReporteUsuarios);

        mnItmInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmInventario.setFont(fuenteH);
        mnItmInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_search_black_18dp.png"))); // NOI18N
        mnItmInventario.setText("Inventario");
        menuConsultas.add(mnItmInventario);

        mbBarraMenu.add(menuConsultas);

        menuLibros.setForeground(Color.BLACK);
        menuLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_menu_bookG.png"))); // NOI18N
        menuLibros.setText("Libros");
        menuLibros.setFont(fuenteT);
        menuLibros.setIconTextGap(10);

        mnItmPrestamoLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmPrestamoLibros.setFont(fuenteH);
        mnItmPrestamoLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_library_books_black_18dp.png"))); // NOI18N
        mnItmPrestamoLibros.setText("Prestamo Libros");
        menuLibros.add(mnItmPrestamoLibros);

        mnItmDevolucionLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmDevolucionLibros.setFont(fuenteH);
        mnItmDevolucionLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_assignment_return_black_18dp.png"))); // NOI18N
        mnItmDevolucionLibros.setText("Devolucion de Libros");
        menuLibros.add(mnItmDevolucionLibros);

        mbBarraMenu.add(menuLibros);

        menuAcerca.setForeground(Color.BLACK);
        menuAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_help_outline_black_18dp.png"))); // NOI18N
        menuAcerca.setFont(fuenteT);
        menuAcerca.setIconTextGap(10);
        menuAcerca.setMargin(new java.awt.Insets(0, 0, 0, 20));

        mnItmAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        mnItmAcerca.setFont(fuenteH);
        mnItmAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_contact_support_black_18dp.png"))); // NOI18N
        mnItmAcerca.setText("Acerca");
        menuAcerca.add(mnItmAcerca);

        mbBarraMenu.add(Box.createHorizontalGlue());

        mbBarraMenu.add(menuAcerca);

        setJMenuBar(mbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar mbBarraMenu;
    private javax.swing.JMenu menuAcerca;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenuItem menuItmSalir;
    private javax.swing.JMenu menuLibros;
    private javax.swing.JMenuItem mnItmAcerca;
    private javax.swing.JMenuItem mnItmAltaLibros;
    private javax.swing.JMenuItem mnItmAltasUsuario;
    private javax.swing.JMenuItem mnItmBusqueda;
    private javax.swing.JMenuItem mnItmDevolucionLibros;
    private javax.swing.JMenuItem mnItmExistencia;
    private javax.swing.JMenuItem mnItmInventario;
    private javax.swing.JMenuItem mnItmMorosos;
    private javax.swing.JMenuItem mnItmPrestamoLibros;
    private javax.swing.JMenuItem mnItmReporteUsuarios;
    // End of variables declaration//GEN-END:variables
}
