/*                    
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appbiblioteca.vistas;


import appbiblioteca.negocio.ManejaEventos;
import appbiblioteca.modelo.Libro;
import appbiblioteca.persistencia.ManejaLista;
import appbiblioteca.persistencia.ManejaTablaH;
import appbiblioteca.modelo.Usuario;
import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import javax.swing.Box;
import recursos.MaterialBtn;
/**
 *
 * @author Jorge
 */
public class VistaBiblioteca extends javax.swing.JFrame {
    
    private final Font fuenteH= new Font("Helvetica",Font.PLAIN,13);
    private final Font fuenteT= new Font("Helvetica",Font.PLAIN,15);
    private final Font fuenteP= new Font("Helvetica",Font.PLAIN,20);
    private final Color COLOR_MEDIO = new Color(0, 176, 255);
    private final Color COLOR_LIGHT = new Color(105, 226, 255);
    private final Color COLOR_DARK = new Color(0, 129, 203);
    
    private ManejaTablaH tablaH;
    private ManejaLista lista;

    public VistaBiblioteca() {
        
        tablaH = new ManejaTablaH();
        lista = new ManejaLista(tablaH);
        initComponents();
        creaAcciones();
        
        // Usuarios Agregados Inicialmente Para hacer Pruebas
        Usuario pedro = new Usuario("PEDRO", "PEREZ", "LOPEZ", "LAS QUINTAS", "CULIACAN", 'A');
        Usuario hernan = new Usuario("HERNAN", "ROSALES", "CORVERA", "POR AHI", "CULIACAN", 'M');
        Usuario armando = new Usuario("ARMANDO", "BELTRAN", "MEDINA", "DOMICILIO CONOCIDO", "CULIACAN", 'E');

        tablaH.getTablaUsuario().AgregaUsuario(pedro);
        tablaH.getTablaUsuario().AgregaUsuario(hernan);
        tablaH.getTablaUsuario().AgregaUsuario(armando);
        
        // Libros Agregados Inicialmente Para Hacer Pruebas
        Libro libro1 = new Libro("GAME OF THRONES", "GEORGE R.R MARTIN",
                "LIBRO DE FANTASIA MEDIEVAL", "NO SE", 5);
        Libro libro2 = new Libro("HARRY POTTER Y LA PIEDRA FILOSOFAL", "J.K ROWLINS", "LIBRO DE FANTASIA MAGICA Y HECHICERIA", "BLOOMSBURY PUBLISHING", 6);
        
        tablaH.getTablaLibro().AgregaLibro(libro1);
        tablaH.getTablaLibro().AgregaLibro(libro2);
                
        pedro.setMoroso(true);
        
    }
    
    private void creaAcciones(){
        
        ManejaEventos controladora = new ManejaEventos(this,tablaH, lista);
        menuItmSalir.addActionListener(controladora);
        mnItmAltasUsuario.addActionListener(controladora);
        mnItmAltaLibros.addActionListener(controladora);
        mnItmExistencia.addActionListener(controladora);
        mnItmPrestamoLibros.addActionListener(controladora);
        mnItmDevolucionLibros.addActionListener(controladora);
        mnItmBusqueda.addActionListener(controladora);
        mnItmReporteUsuarios.addActionListener(controladora);
        mnItmAcerca.addActionListener(controladora);
        mnItmInventario.addActionListener(controladora);
        mnItmMorosos.addActionListener(controladora);
        lblInventario.addMouseListener(controladora);
        lblMorosos.addMouseListener(controladora);
        lblPrestamos.addMouseListener(controladora);
        lblUsuario.addMouseListener(controladora);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlContenedor = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblInventario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblPrestamos = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblMorosos = new javax.swing.JLabel();
        mbBarraMenu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuItmSalir = new javax.swing.JMenuItem();
        menuGestion = new javax.swing.JMenu();
        mnItmAltasUsuario = new javax.swing.JMenuItem();
        mnItmAltaLibros = new javax.swing.JMenuItem();
        mnItmExistencia = new javax.swing.JMenuItem();
        mnItmMorosos = new javax.swing.JMenuItem();
        menuConsultas = new javax.swing.JMenu();
        mnItmBusqueda = new javax.swing.JMenuItem();
        mnItmReporteUsuarios = new javax.swing.JMenuItem();
        mnItmInventario = new javax.swing.JMenuItem();
        menuLibros = new javax.swing.JMenu();
        mnItmPrestamoLibros = new javax.swing.JMenuItem();
        mnItmDevolucionLibros = new javax.swing.JMenuItem();
        menuAcerca = new javax.swing.JMenu();
        mnItmAcerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setBackground(Color.WHITE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/recursos/2x/book-2-24.png")));
        setLocationByPlatform(true);
        setName("VistaBiblioteca"); // NOI18N
        setResizable(false);

        pnlContenedor.setLayout(new java.awt.GridLayout(2, 2, 5, 5));

        jPanel1.setBackground(COLOR_LIGHT);

        jLabel1.setFont(fuenteP);
        jLabel1.setText("Inventario");

        lblInventario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_find_in_page_black_18dp.png"))); // NOI18N
        lblInventario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInventario.setName("Inventario"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(lblInventario)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(78, 78, 78)
                .addComponent(lblInventario)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pnlContenedor.add(jPanel1);

        jPanel2.setBackground(COLOR_DARK);

        jLabel2.setFont(fuenteP);
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Usuarios");

        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_person_search_black_18dp.png"))); // NOI18N
        lblUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblUsuario.setName("Usuarios"); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addGap(171, 171, 171))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(76, 76, 76)
                .addComponent(lblUsuario)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        pnlContenedor.add(jPanel2);

        jPanel3.setBackground(COLOR_DARK);

        jLabel3.setFont(fuenteP);
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Prestamos");

        lblPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPrestamos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_libraryG.png"))); // NOI18N
        lblPrestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPrestamos.setName("Prestamos"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(lblPrestamos)))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(88, 88, 88)
                .addComponent(lblPrestamos)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pnlContenedor.add(jPanel3);

        jPanel4.setBackground(COLOR_LIGHT);

        jLabel4.setFont(fuenteP);
        jLabel4.setText("Morosos");

        lblMorosos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMorosos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_disabled_by_default_black_18dp.png"))); // NOI18N
        lblMorosos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblMorosos.setName("Morosos"); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(lblMorosos)
                .addGap(169, 169, 169))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(81, 81, 81)
                .addComponent(lblMorosos)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pnlContenedor.add(jPanel4);

        mbBarraMenu.setBackground(COLOR_MEDIO);
        mbBarraMenu.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, COLOR_LIGHT, COLOR_MEDIO, COLOR_DARK, COLOR_MEDIO));

        menuArchivo.setForeground(Color.BLACK);
        menuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_menuG.png"))); // NOI18N
        menuArchivo.setText("Archivo");
        menuArchivo.setFont(fuenteT);
        menuArchivo.setIconTextGap(10);

        menuItmSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        menuItmSalir.setFont(fuenteH);
        menuItmSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_close_black_18dp.png"))); // NOI18N
        menuItmSalir.setText("Salir");
        menuArchivo.add(menuItmSalir);

        mbBarraMenu.add(menuArchivo);

        menuGestion.setForeground(Color.BLACK);
        menuGestion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_addG.png"))); // NOI18N
        menuGestion.setText("Gestion");
        menuGestion.setFont(fuenteT);
        menuGestion.setIconTextGap(10);

        mnItmAltasUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmAltasUsuario.setFont(fuenteH);
        mnItmAltasUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_person_add_black_18dp.png"))); // NOI18N
        mnItmAltasUsuario.setText("Altas Usuario");
        menuGestion.add(mnItmAltasUsuario);

        mnItmAltaLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmAltaLibros.setFont(fuenteH);
        mnItmAltaLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_library_add_black_18dp.png"))); // NOI18N
        mnItmAltaLibros.setText("Alta Libros");
        menuGestion.add(mnItmAltaLibros);

        mnItmExistencia.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmExistencia.setFont(fuenteH);
        mnItmExistencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_addchart_black_18dp.png"))); // NOI18N
        mnItmExistencia.setText("Aumentar Existencia");
        menuGestion.add(mnItmExistencia);

        mnItmMorosos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmMorosos.setFont(fuenteH);
        mnItmMorosos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_disabled_by_default_black_18dp.png"))); // NOI18N
        mnItmMorosos.setText("Morosos");
        menuGestion.add(mnItmMorosos);

        mbBarraMenu.add(menuGestion);

        menuConsultas.setForeground(Color.BLACK);
        menuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_search_black_18dp.png"))); // NOI18N
        menuConsultas.setText("Consultas");
        menuConsultas.setFont(fuenteT);
        menuConsultas.setIconTextGap(10);

        mnItmBusqueda.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmBusqueda.setFont(fuenteH);
        mnItmBusqueda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_search_black_18dp.png"))); // NOI18N
        mnItmBusqueda.setText("Busqueda");
        menuConsultas.add(mnItmBusqueda);

        mnItmReporteUsuarios.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmReporteUsuarios.setFont(fuenteH);
        mnItmReporteUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_person_search_black_18dp.png"))); // NOI18N
        mnItmReporteUsuarios.setText("Reporte Usuarios");
        menuConsultas.add(mnItmReporteUsuarios);

        mnItmInventario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmInventario.setFont(fuenteH);
        mnItmInventario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_find_in_page_black_18dp.png"))); // NOI18N
        mnItmInventario.setText("Inventario");
        menuConsultas.add(mnItmInventario);

        mbBarraMenu.add(menuConsultas);

        menuLibros.setForeground(Color.BLACK);
        menuLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_menu_bookG.png"))); // NOI18N
        menuLibros.setText("Libros");
        menuLibros.setFont(fuenteT);
        menuLibros.setIconTextGap(10);

        mnItmPrestamoLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmPrestamoLibros.setFont(fuenteH);
        mnItmPrestamoLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_library_books_black_18dp.png"))); // NOI18N
        mnItmPrestamoLibros.setText("Prestamo Libros");
        menuLibros.add(mnItmPrestamoLibros);

        mnItmDevolucionLibros.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        mnItmDevolucionLibros.setFont(fuenteH);
        mnItmDevolucionLibros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_assignment_return_black_18dp.png"))); // NOI18N
        mnItmDevolucionLibros.setText("Devolucion de Libros");
        menuLibros.add(mnItmDevolucionLibros);

        mbBarraMenu.add(menuLibros);

        menuAcerca.setForeground(Color.BLACK);
        menuAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/2x/baseline_help_outline_black_18dp.png"))); // NOI18N
        menuAcerca.setFont(fuenteT);
        menuAcerca.setIconTextGap(10);
        menuAcerca.setMargin(new java.awt.Insets(0, 0, 0, 20));

        mnItmAcerca.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        mnItmAcerca.setFont(fuenteH);
        mnItmAcerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/1x/baseline_contact_support_black_18dp.png"))); // NOI18N
        mnItmAcerca.setText("Acerca");
        menuAcerca.add(mnItmAcerca);

        mbBarraMenu.add(Box.createHorizontalGlue());

        mbBarraMenu.add(menuAcerca);

        setJMenuBar(mbBarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblInventario;
    private javax.swing.JLabel lblMorosos;
    private javax.swing.JLabel lblPrestamos;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JMenuBar mbBarraMenu;
    private javax.swing.JMenu menuAcerca;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenu menuConsultas;
    private javax.swing.JMenu menuGestion;
    private javax.swing.JMenuItem menuItmSalir;
    private javax.swing.JMenu menuLibros;
    private javax.swing.JMenuItem mnItmAcerca;
    private javax.swing.JMenuItem mnItmAltaLibros;
    private javax.swing.JMenuItem mnItmAltasUsuario;
    private javax.swing.JMenuItem mnItmBusqueda;
    private javax.swing.JMenuItem mnItmDevolucionLibros;
    private javax.swing.JMenuItem mnItmExistencia;
    private javax.swing.JMenuItem mnItmInventario;
    private javax.swing.JMenuItem mnItmMorosos;
    private javax.swing.JMenuItem mnItmPrestamoLibros;
    private javax.swing.JMenuItem mnItmReporteUsuarios;
    private javax.swing.JPanel pnlContenedor;
    // End of variables declaration//GEN-END:variables
}
